Repository HH8-5-SeaTudy/BE_SeaTudy, pull requests merged in 2022-09, with the labels that each got.

#26 [Todocategory] Pull Request
  src/main/java/com/finalproject/seatudy/domain/entity/TodoCategory.java
  src/main/java/com/finalproject/seatudy/domain/repository/TodoCategoryRepository.java
  src/main/java/com/finalproject/seatudy/interfaces/TodoCategoryController.java
  src/main/java/com/finalproject/seatudy/service/DdayService.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/dto/request/DdayRequestDto.java
  src/main/java/com/finalproject/seatudy/service/dto/request/TodoCategoryRequestDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoCateShortResDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoCategoryResponseDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoListResponseDto.java
  src/test/java/com/finalproject/seatudy/login/naver/NaverMemberServiceTest.java
Labels: enhancement

#31 perf: TodoCategory와 TodoList의 생성시 동일날짜에 들어가게 수정 #30
  src/main/java/com/finalproject/seatudy/service/TodoListService.java
Labels: perf

#35 [ci/cd] pull request
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/cicd_application.properties
Labels: enhancement

#36 [Exception] pull request - 1
  src/main/java/com/finalproject/seatudy/security/exception/AuthenticationFailHandler.java
  src/main/java/com/finalproject/seatudy/security/exception/CustomExceptionHandler.java
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
  src/main/java/com/finalproject/seatudy/security/filter/JwtAuthFilter.java
  src/main/java/com/finalproject/seatudy/security/jwt/HeaderTokenExtractor.java
  src/main/java/com/finalproject/seatudy/security/jwt/JwtDecoder.java
  src/main/java/com/finalproject/seatudy/security/jwt/JwtTokenUtils.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/TodoListService.java
Labels: perf

#39 Todolist, TodoCategory Response 및 예외처리 수정
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/TodoListService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoListResponseDto.java
Labels: bug, refactor

#41 [TodoCategory] Response 수정 후 pull request
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
Labels: perf

#42 [Exception] pull request
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
  src/main/java/com/finalproject/seatudy/service/DdayService.java
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/DdayResponseDto.java
Labels: perf

#44 [Websocket] pull request after fix
  src/main/java/com/finalproject/seatudy/interfaces/chat/ChatController.java
  src/main/java/com/finalproject/seatudy/security/config/WebSecurityConfig.java
  src/main/java/com/finalproject/seatudy/security/config/WebSocketConfig.java
Labels: bug

#46 perf: Todocategory&Todolist 추가 예외처리 및 코드 수정완료 #45
  src/main/java/com/finalproject/seatudy/domain/entity/TodoList.java
  src/main/java/com/finalproject/seatudy/domain/repository/TodoCategoryRepository.java
  src/main/java/com/finalproject/seatudy/domain/repository/TodoListRepository.java
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/TodoListService.java
Labels: perf

#48 [Websocket] perf: 예외처리 후 pull request
  src/main/java/com/finalproject/seatudy/interfaces/chat/ChatController.java
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
Labels: perf

#51 [TimeCheck] pull request
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TimeCheckListDto.java
Labels: perf

#52 [build] pull request
  src/main/java/com/finalproject/seatudy/security/config/WebSecurityConfig.java
  src/main/java/com/finalproject/seatudy/security/config/WebSocketConfig.java
Labels: refactor

#53 [build] pull request
  src/main/java/com/finalproject/seatudy/security/config/WebSecurityConfig.java
  src/main/java/com/finalproject/seatudy/security/config/WebSocketConfig.java
Labels: bug

#57 [build] pull request
  src/main/java/com/finalproject/seatudy/security/config/WebSecurityConfig.java
  src/main/resources/cicd_application.properties
Labels: refactor

#61 [CI/ CD] application.properties 오류 fix re-try
  .github/workflows/deploy.yml
  src/main/resources/seatudy_application.properties
Labels: bug

#62 [CI/ CD] application.properties 파일명 수정
  .github/workflows/deploy.yml
Labels: bug

#64 fix: TodocategoryService 오류코드 수정 및 카테고리Update RequestDto 코드 변경 #63
  src/main/java/com/finalproject/seatudy/interfaces/TodoCategoryController.java
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/dto/request/TodoCategoryRequestDto.java
Labels: bug

#71 perf: D-day Response 수정
  src/main/java/com/finalproject/seatudy/interfaces/DdayContoller.java
  src/main/java/com/finalproject/seatudy/service/DdayService.java
Labels: perf

#73 [MyProfile] Pull request
  src/main/java/com/finalproject/seatudy/domain/entity/Member.java
  src/main/java/com/finalproject/seatudy/infra/GoogleMemberService.java
  src/main/java/com/finalproject/seatudy/infra/KaKaoMemberService.java
  src/main/java/com/finalproject/seatudy/infra/NaverMemberService.java
  src/main/java/com/finalproject/seatudy/interfaces/MemberController.java
  src/main/java/com/finalproject/seatudy/service/MemberService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MemberResDto.java
Labels: enhancement

#77 [TodoCategory] Pull Request
  src/main/java/com/finalproject/seatudy/domain/repository/TodoCategoryRepository.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
Labels: enhancement

#79 [D-day] pull request
  src/main/java/com/finalproject/seatudy/interfaces/DdayContoller.java
  src/main/java/com/finalproject/seatudy/service/DdayService.java
Labels: enhancement

#82 [Rank] pull request
  src/main/java/com/finalproject/seatudy/domain/entity/Rank.java
  src/main/java/com/finalproject/seatudy/domain/entity/WeekRank.java
  src/main/java/com/finalproject/seatudy/domain/repository/RankRepository.java
  src/main/java/com/finalproject/seatudy/domain/repository/WeekRankRepository.java
  src/main/java/com/finalproject/seatudy/interfaces/RankController.java
  src/main/java/com/finalproject/seatudy/service/RankService.java
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/DayStudyResponseDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/RankResponseDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/WeekRankResponseDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/WeekStudyDetailResponseDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/WeekStudyResponseDto.java
Labels: enhancement

#84 [MyProfile] pull request
  src/main/java/com/finalproject/seatudy/domain/entity/Fish.java
  src/main/java/com/finalproject/seatudy/domain/entity/Member.java
  src/main/java/com/finalproject/seatudy/domain/repository/FishRepository.java
  src/main/java/com/finalproject/seatudy/domain/repository/MemberRepository.java
  src/main/java/com/finalproject/seatudy/infra/GoogleMemberService.java
  src/main/java/com/finalproject/seatudy/infra/KaKaoMemberService.java
  src/main/java/com/finalproject/seatudy/infra/NaverMemberService.java
  src/main/java/com/finalproject/seatudy/interfaces/MemberController.java
  src/main/java/com/finalproject/seatudy/service/MemberService.java
  src/main/java/com/finalproject/seatudy/service/dto/request/FishReqDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/FishInfoResDto.java
Labels: enhancement

#83 [Todocategory] Pull Request
  src/main/java/com/finalproject/seatudy/security/exception/ErrorCode.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MemberCateDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoCategoryResponseDto.java
Labels: refactor

#86 [Todolist] Pull Request
  src/main/java/com/finalproject/seatudy/domain/entity/TodoList.java
  src/main/java/com/finalproject/seatudy/interfaces/TodoListController.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
  src/main/java/com/finalproject/seatudy/service/TodoListService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoListResponseDto.java
Labels: refactor

#89 [Rank] pull request
  src/main/java/com/finalproject/seatudy/domain/entity/WeekRank.java
  src/main/java/com/finalproject/seatudy/domain/repository/WeekRankRepository.java
  src/main/java/com/finalproject/seatudy/interfaces/RankController.java
  src/main/java/com/finalproject/seatudy/service/RankService.java
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/DayStudyResponseDto.java
Labels: perf

#91 [Member] pull request
  src/main/java/com/finalproject/seatudy/service/MemberService.java
  src/main/java/com/finalproject/seatudy/service/dto/request/NicknameReqDto.java
Labels: bug

#92 [Member] pull request
  src/main/java/com/finalproject/seatudy/infra/GoogleMemberService.java
  src/main/java/com/finalproject/seatudy/infra/KaKaoMemberService.java
  src/main/java/com/finalproject/seatudy/infra/NaverMemberService.java
  src/main/java/com/finalproject/seatudy/service/MemberService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MemberResDto.java
Labels: refactor

#93 [Member] pull request
  src/main/java/com/finalproject/seatudy/infra/NaverMemberService.java
Labels: refactor

#94 [TimeCheck][Rank] pull request
  src/main/java/com/finalproject/seatudy/interfaces/RankController.java
  src/main/java/com/finalproject/seatudy/service/RankService.java
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TimeCheckListDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/TodoCateShortResDto.java
Labels: refactor

#96 [Rank] pull request
  src/main/java/com/finalproject/seatudy/service/dto/response/RankResponseDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/WeekRankResponseDto.java
Labels: perf

#99 [FishLocation]pull request
  src/main/java/com/finalproject/seatudy/domain/entity/FishLocation.java
  src/main/java/com/finalproject/seatudy/domain/repository/FishLocationRepository.java
  src/main/java/com/finalproject/seatudy/interfaces/FishLocationController.java
  src/main/java/com/finalproject/seatudy/service/FishLocationService.java
  src/main/java/com/finalproject/seatudy/service/dto/request/FishLocationReqDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/FishLocationResDto.java
Labels: enhancement

#106 [Rank] pull request
  src/main/java/com/finalproject/seatudy/domain/repository/WeekRankRepository.java
  src/main/java/com/finalproject/seatudy/interfaces/RankController.java
  src/main/java/com/finalproject/seatudy/service/RankService.java
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MyRankResponseDto.java
Labels: perf

#108 [TimeCheck] pull request
  src/main/java/com/finalproject/seatudy/service/TimeCheckService.java
Labels: bug
