Repository HH8-5-SeaTudy/BE_SeaTudy, pull requests merged in 2022-10, with the labels that each got.

#110 [Rank] pull request
  src/main/java/com/finalproject/seatudy/domain/repository/RankRepository.java
  src/main/java/com/finalproject/seatudy/domain/repository/WeekRankRepository.java
  src/main/java/com/finalproject/seatudy/service/RankService.java
Labels: perf

#113 [MyProfle] pull request
  src/main/java/com/finalproject/seatudy/service/MemberService.java
  src/main/java/com/finalproject/seatudy/service/RankService.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MemberResDto.java
Labels: perf

#115 [Chat] pull request
  src/main/java/com/finalproject/seatudy/domain/repository/ChatRoomRepository.java
  src/main/java/com/finalproject/seatudy/domain/repository/RankRepository.java
  src/main/java/com/finalproject/seatudy/domain/repository/WeekRankRepository.java
  src/main/java/com/finalproject/seatudy/interfaces/FishLocationController.java
  src/main/java/com/finalproject/seatudy/security/StompHandler.java
  src/main/java/com/finalproject/seatudy/service/ChatRoomService.java
  src/main/java/com/finalproject/seatudy/service/dto/request/ChatMessageDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MemberResDto.java
Labels: perf

#118 [todolist] pull request
  src/main/java/com/finalproject/seatudy/domain/repository/TodoCategoryRepository.java
  src/main/java/com/finalproject/seatudy/service/TodoCategoryService.java
Labels: bug

#119 [chatroom] pull request
  src/main/java/com/finalproject/seatudy/security/StompHandler.java
Labels: perf, test

#120 [FishLocation] pull request
  src/main/java/com/finalproject/seatudy/interfaces/FishLocationController.java
  src/main/java/com/finalproject/seatudy/service/FishLocationService.java
Labels: enhancement

#121 [Chat] pull request
  src/main/java/com/finalproject/seatudy/domain/repository/ChatRoomRepository.java
  src/main/java/com/finalproject/seatudy/security/StompHandler.java
  src/main/java/com/finalproject/seatudy/service/dto/request/ChatMessageDto.java
  src/main/java/com/finalproject/seatudy/service/dto/response/MemberResDto.java
Labels: perf
